<?php
   $this->load->view('landing_page/layout/header');
   ?>

   
    <link rel="stylesheet" href="<?=base_url()?>assets/costum/maps/leaflet.css" />
   <!--[if lte IE 8]><link rel="stylesheet" href="<?=base_url()?>assets/costum/maps/leaflet.ie.css" /><![endif]-->
   
   <script src="<?=base_url()?>assets/costum/maps/leaflet.js"></script>

    <div class="wheel-start3">
            <img src="images/bg1.jpeg" alt="" class="wheel-img">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 padd-lr0">
                        <div class="wheel-start3-body clearfix marg-lg-t255 marg-lg-b75 marg-sm-t190 marg-xs-b30">
                            <h3>Services</h3>
                            <ol class="breadcrumb">
                                <li><a href="#">Home</a></li>
                                <li><a href="#"> pages </a></li>
                                <li class="active">Services</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- //////////////////////////////////////////// -->
        <div style="margin-bottom:100px;">
            <div class="row">
                <div class="col-md-12 padd-lr0">
                    <div id="map" style="height: 500px"></div>
                </div>
            </div>
        </div>
        <!-- //////////////////////////////////////////// -->
        <div class="container">
            <div class="row">
                <div class="col-md-12 padd-lr0">
                    <div class="wheel-skills marg-lg-b150 marg-sm-b50">
                        <div class="tabs-item text-item active">
                            <ul class="tabslist">
                                <li class="item">Banjarmasin</li>
                                <li class="item">Bandung</li>
                                <li class="item">Dki Jakarta</li>
                                <li class="item">Kudus</li>
                            </ul>
                            <ul class="tabslist">
                                <li class="item">Banjarmasin</li>
                                <li class="item">Bandung</li>
                                <li class="item">Dki Jakarta</li>
                                <li class="item">Kudus</li>
                            </ul>
                            <ul class="tabslist">
                                <li class="item">Banjarmasin</li>
                                <li class="item">Bandung</li>
                                <li class="item">Dki Jakarta</li>
                                <li class="item">Kudus</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script language="javascript">
      function maps() {
         var map = new L.Map('map');                       
                
      	 L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors',
            maxZoom: 5
         }).addTo(map);
         map.attributionControl.setPrefix(''); // Don't show the 'Powered by Leaflet' text.

         var indonesia = new L.LatLng( -3.409518, 115.188919 ); 
         map.setView(indonesia, 13);
         map.scrollWheelZoom.disable();
         var greenIcon = L.icon({
            iconUrl: '<?=base_url()?>assets/costum/maps/pin.svg',

            iconSize:     [38, 95], // size of the icon
            iconAnchor:   [20, 70], // point of the icon which will correspond to marker's location
            shadowAnchor: [4, 62],  // the same for the shadow
            popupAnchor:  [-2, -40] // point from which the popup should open relative to the iconAnchor
        });
         
         
         // Define an array. This could be done in a seperate js file.
         // This tidy formatted section could even be generated by a server-side script
         // or fetched seperately as a jsonp request.
         var markers = [
            [ -7.161367,113.482498,  "Pamekasan" ],
            [   -7.025253,107.519760,"Bandung"],
            [  0.000000,109.333336, "Pontianak" ] 
         ];
         
         //Loop through the markers array
         for (var i=0; i<markers.length; i++) {
           
            var lon = markers[i][1];
            var lat = markers[i][0];
            var popupText = markers[i][2];
            
             var markerLocation = new L.LatLng(lat, lon);
             var marker = new L.Marker(markerLocation,{icon: greenIcon});
             map.addLayer(marker);
         
             marker.bindPopup(popupText);
         
         }

      }
   </script>
   <script> 
    // $( document ).ready(function() {
            maps();
    //     });
   </script>

<?php
   $this->load->view('landing_page/layout/footer');
   ?>